set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]

# GCLK 12MHZ Tied to USB
create_clock -period 83.330 -name GCLK [get_ports GCLK]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports GCLK]


# Buttons
set_property -dict {PACKAGE_PIN A18 IOSTANDARD LVCMOS33} [get_ports BTN0]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD LVCMOS33} [get_ports BTN1]

# LEDs
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS33} [get_ports {LED[0]}]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports {LED[1]}]

# RGB LED
set_property -dict {PACKAGE_PIN B17 IOSTANDARD LVCMOS33} [get_ports LED0_B]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD LVCMOS33} [get_ports LED0_G]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD LVCMOS33} [get_ports LED0_R]

# UART
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports UART_RXD_OUT]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports UART_TXD_IN]

# GPIO Pins
# Pins 15 and 16 should remain commented if using them as analog inputs
#set_property -dict { PACKAGE_PIN M3    IOSTANDARD LVCMOS33 } [get_ports { pio[01] }]; #IO_L8N_T1_AD14N_35 Sch=pio[01]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports clk_out]
#set_property -dict { PACKAGE_PIN L3    IOSTANDARD LVCMOS33 } [get_ports { pio[02] }]; #IO_L8P_T1_AD14P_35 Sch=pio[02]
#set_property -dict { PACKAGE_PIN A16   IOSTANDARD LVCMOS33 } [get_ports { pio[03] }]; #IO_L12P_T1_MRCC_16 Sch=pio[03]
#set_property -dict { PACKAGE_PIN K3    IOSTANDARD LVCMOS33 } [get_ports { pio[04] }]; #IO_L7N_T1_AD6N_35 Sch=pio[04]
#set_property -dict { PACKAGE_PIN C15   IOSTANDARD LVCMOS33 } [get_ports { pio[05] }]; #IO_L11P_T1_SRCC_16 Sch=pio[05]
#set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports { pio[06] }]; #IO_L3P_T0_DQS_AD5P_35 Sch=pio[06]
#set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVCMOS33 } [get_ports { pio[07] }]; #IO_L6N_T0_VREF_16 Sch=pio[07]
set_property -dict { PACKAGE_PIN A15   IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_1 }];
#set_property -dict { PACKAGE_PIN B15   IOSTANDARD LVCMOS33 } [get_ports { pio[08] }]; #IO_L11N_T1_SRCC_16 Sch=pio[08]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports PIO1]
#set_property -dict { PACKAGE_PIN A14   IOSTANDARD LVCMOS33 } [get_ports { pio[09] }]; #IO_L6P_T0_16 Sch=pio[09]
#set_property -dict { PACKAGE_PIN J3    IOSTANDARD LVCMOS33 } [get_ports { pio[10] }]; #IO_L7P_T1_AD6P_35 Sch=pio[10]
#set_property -dict { PACKAGE_PIN J1    IOSTANDARD LVCMOS33 } [get_ports { pio[11] }]; #IO_L3N_T0_DQS_AD5N_35 Sch=pio[11]
#set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { pio[12] }]; #IO_L5P_T0_AD13P_35 Sch=pio[12]
set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_2 }]; #IO_L5P_T0_AD13P_35 Sch=pio[12]
#set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports { pio[13] }]; #IO_L6N_T0_VREF_35 Sch=pio[13]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports PIO2]
#set_property -dict { PACKAGE_PIN L2    IOSTANDARD LVCMOS33 } [get_ports { pio[14] }]; #IO_L5N_T0_AD13N_35 Sch=pio[14]
#set_property -dict { PACKAGE_PIN M1    IOSTANDARD LVCMOS33 } [get_ports { pio[17] }]; #IO_L9N_T1_DQS_AD7N_35 Sch=pio[17]
set_property -dict { PACKAGE_PIN M1    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_3 }];
#set_property -dict { PACKAGE_PIN N3    IOSTANDARD LVCMOS33 } [get_ports { pio[18] }]; #IO_L12P_T1_MRCC_35 Sch=pio[18]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD LVCMOS33} [get_ports PIO3]
#set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports { pio[19] }]; #IO_L12N_T1_MRCC_35 Sch=pio[19]
#set_property -dict { PACKAGE_PIN M2    IOSTANDARD LVCMOS33 } [get_ports { pio[20] }]; #IO_L9P_T1_DQS_AD7P_35 Sch=pio[20]
#set_property -dict { PACKAGE_PIN N1    IOSTANDARD LVCMOS33 } [get_ports { pio[21] }]; #IO_L10N_T1_AD15N_35 Sch=pio[21]
#set_property -dict { PACKAGE_PIN N2    IOSTANDARD LVCMOS33 } [get_ports { pio[22] }]; #IO_L10P_T1_AD15P_35 Sch=pio[22]
set_property -dict { PACKAGE_PIN N2    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_4 }];
#set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports { pio[23] }]; #IO_L19N_T3_VREF_35 Sch=pio[23]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports PIO4]
#set_property -dict { PACKAGE_PIN R3    IOSTANDARD LVCMOS33 } [get_ports { pio[26] }]; #IO_L2P_T0_34 Sch=pio[26]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD LVCMOS33} [get_ports PIO5]
#set_property -dict { PACKAGE_PIN T3    IOSTANDARD LVCMOS33 } [get_ports { pio[27] }]; #IO_L2N_T0_34 Sch=pio[27]
set_property -dict { PACKAGE_PIN T3    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_5 }];
#set_property -dict { PACKAGE_PIN R2    IOSTANDARD LVCMOS33 } [get_ports { pio[28] }]; #IO_L1P_T0_34 Sch=pio[28]
#set_property -dict { PACKAGE_PIN T1    IOSTANDARD LVCMOS33 } [get_ports { pio[29] }]; #IO_L3P_T0_DQS_34 Sch=pio[29]
#set_property -dict { PACKAGE_PIN T2    IOSTANDARD LVCMOS33 } [get_ports { pio[30] }]; #IO_L1N_T0_34 Sch=pio[30]
#set_property -dict { PACKAGE_PIN U1    IOSTANDARD LVCMOS33 } [get_ports { pio[31] }]; #IO_L3N_T0_DQS_34 Sch=pio[31]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports PIO6]
#set_property -dict { PACKAGE_PIN W2    IOSTANDARD LVCMOS33 } [get_ports { pio[32] }]; #IO_L5N_T0_34 Sch=pio[32]
set_property -dict { PACKAGE_PIN W2    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_6 }];
#set_property -dict { PACKAGE_PIN V2    IOSTANDARD LVCMOS33 } [get_ports { pio[33] }]; #IO_L5P_T0_34 Sch=pio[33]
#set_property -dict { PACKAGE_PIN W3    IOSTANDARD LVCMOS33 } [get_ports { pio[34] }]; #IO_L6N_T0_VREF_34 Sch=pio[34]
#set_property -dict { PACKAGE_PIN V3    IOSTANDARD LVCMOS33 } [get_ports { pio[35] }]; #IO_L6P_T0_34 Sch=pio[35]
#set_property -dict { PACKAGE_PIN W5    IOSTANDARD LVCMOS33 } [get_ports { pio[36] }]; #IO_L12P_T1_MRCC_34 Sch=pio[36]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports PIO7]
#set_property -dict { PACKAGE_PIN V4    IOSTANDARD LVCMOS33 } [get_ports { pio[37] }]; #IO_L11N_T1_SRCC_34 Sch=pio[37]
set_property -dict { PACKAGE_PIN V4    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_7 }];
#set_property -dict { PACKAGE_PIN U4    IOSTANDARD LVCMOS33 } [get_ports { pio[38] }]; #IO_L11P_T1_SRCC_34 Sch=pio[38]
#set_property -dict { PACKAGE_PIN V5    IOSTANDARD LVCMOS33 } [get_ports { pio[39] }]; #IO_L16N_T2_34 Sch=pio[39]
#set_property -dict { PACKAGE_PIN W4    IOSTANDARD LVCMOS33 } [get_ports { pio[40] }]; #IO_L12N_T1_MRCC_34 Sch=pio[40]
#set_property -dict { PACKAGE_PIN U5    IOSTANDARD LVCMOS33 } [get_ports { pio[41] }]; #IO_L16P_T2_34 Sch=pio[41]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports PIO8]
#set_property -dict { PACKAGE_PIN U2    IOSTANDARD LVCMOS33 } [get_ports { pio[42] }]; #IO_L9N_T1_DQS_34 Sch=pio[42]
set_property -dict { PACKAGE_PIN U2    IOSTANDARD LVCMOS33 } [get_ports { gnd_pins_8 }];
#set_property -dict { PACKAGE_PIN W6    IOSTANDARD LVCMOS33 } [get_ports { pio[43] }]; #IO_L13N_T2_MRCC_34 Sch=pio[43]
#set_property -dict { PACKAGE_PIN U3    IOSTANDARD LVCMOS33 } [get_ports { pio[44] }]; #IO_L9P_T1_DQS_34 Sch=pio[44]
#set_property -dict { PACKAGE_PIN U7    IOSTANDARD LVCMOS33 } [get_ports { pio[45] }]; #IO_L19P_T3_34 Sch=pio[45]
#set_property -dict { PACKAGE_PIN W7    IOSTANDARD LVCMOS33 } [get_ports { pio[46] }]; #IO_L13P_T2_MRCC_34 Sch=pio[46]
#set_property -dict { PACKAGE_PIN U8    IOSTANDARD LVCMOS33 } [get_ports { pio[47] }]; #IO_L14P_T2_SRCC_34 Sch=pio[47]
#set_property -dict { PACKAGE_PIN V8    IOSTANDARD LVCMOS33 } [get_ports { pio[48] }]; #IO_L14N_T2_SRCC_34 Sch=pio[48]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD LVCMOS33} [get_ports usrp_trigger]

#set_false_path -from [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT0]]
#
set_multicycle_path -from [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT0]] 5
set_multicycle_path -hold -from [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins u_clk_gen/inst/mmcm_adv_inst/CLKOUT0]] 4

set_property MARK_DEBUG true [get_nets u_seq_ctr_1/manchester_wren10_out]

set_property MARK_DEBUG true [get_nets {seq_addr_1[0]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[2]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[3]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[6]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[1]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[4]}]
set_property MARK_DEBUG true [get_nets {seq_addr_1[5]}]

set_property MARK_DEBUG false [get_nets btn0]
set_property MARK_DEBUG false [get_nets btn1]
set_property MARK_DEBUG true [get_nets btn0_int]

set_property MARK_DEBUG false [get_nets {debounce_switch_inst/out[0]}]
set_property MARK_DEBUG false [get_nets {debounce_switch_inst/out[1]}]


set_property MARK_DEBUG true [get_nets {seq_addr_2[0]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[1]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[2]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[3]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[4]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[5]}]
set_property MARK_DEBUG true [get_nets {seq_addr_2[6]}]
set_property MARK_DEBUG true [get_nets trig_1]



set_property MARK_DEBUG false [get_nets trig_2]

set_property MARK_DEBUG false [get_nets dout_1]



set_property MARK_DEBUG false [get_nets {din_5[18]}]
set_property MARK_DEBUG false [get_nets {din_50[6]}]
set_property MARK_DEBUG false [get_nets {din_60[11]}]
set_property MARK_DEBUG false [get_nets {din_70[4]}]
set_property MARK_DEBUG false [get_nets {din_1[17]}]
set_property MARK_DEBUG false [get_nets {din_4[6]}]
set_property MARK_DEBUG false [get_nets {din_1[11]}]
set_property MARK_DEBUG false [get_nets {din_6[4]}]
set_property MARK_DEBUG false [get_nets {din_80[15]}]
set_property MARK_DEBUG false [get_nets {din_50[0]}]
set_property MARK_DEBUG false [get_nets {din_4[2]}]
set_property MARK_DEBUG false [get_nets {din_30[14]}]
set_property MARK_DEBUG false [get_nets {din_3[22]}]
set_property MARK_DEBUG false [get_nets {din_3[17]}]
set_property MARK_DEBUG false [get_nets {din_10[2]}]
set_property MARK_DEBUG false [get_nets {din_20[5]}]
set_property MARK_DEBUG false [get_nets {din_2[9]}]
set_property MARK_DEBUG false [get_nets {din_1[18]}]
set_property MARK_DEBUG false [get_nets {din_5[2]}]
set_property MARK_DEBUG false [get_nets {din_20[7]}]
set_property MARK_DEBUG false [get_nets {din_30[2]}]
set_property MARK_DEBUG false [get_nets {din_30[7]}]
set_property MARK_DEBUG false [get_nets {din_40[10]}]
set_property MARK_DEBUG false [get_nets {din_40[14]}]
set_property MARK_DEBUG false [get_nets {din_1[14]}]
set_property MARK_DEBUG false [get_nets {din_3[12]}]
set_property MARK_DEBUG false [get_nets {din_4[10]}]
set_property MARK_DEBUG false [get_nets {din_5[5]}]
set_property MARK_DEBUG false [get_nets {din_5[8]}]
set_property MARK_DEBUG false [get_nets {din_2[34]}]
set_property MARK_DEBUG false [get_nets {din_2[25]}]
set_property MARK_DEBUG false [get_nets {din_1[3]}]
set_property MARK_DEBUG false [get_nets {din_1[9]}]
set_property MARK_DEBUG false [get_nets {din_3[9]}]
set_property MARK_DEBUG false [get_nets {din_4[11]}]
set_property MARK_DEBUG false [get_nets {din_4[15]}]
set_property MARK_DEBUG false [get_nets {din_4[19]}]
set_property MARK_DEBUG false [get_nets {din_4[23]}]
set_property MARK_DEBUG false [get_nets {din_4[33]}]
set_property MARK_DEBUG false [get_nets {din_5[21]}]
set_property MARK_DEBUG false [get_nets {din_40[2]}]
set_property MARK_DEBUG false [get_nets {din_40[6]}]
set_property MARK_DEBUG false [get_nets {din_5[25]}]
set_property MARK_DEBUG false [get_nets {din_3[24]}]
set_property MARK_DEBUG false [get_nets {din_3[3]}]
set_property MARK_DEBUG false [get_nets {din_20[11]}]
set_property MARK_DEBUG false [get_nets {din_20[15]}]
set_property MARK_DEBUG false [get_nets {din_2[21]}]
set_property MARK_DEBUG false [get_nets {din_2[17]}]
set_property MARK_DEBUG false [get_nets {din_2[12]}]
set_property MARK_DEBUG false [get_nets {din_2[7]}]
set_property MARK_DEBUG false [get_nets {din_2[1]}]
set_property MARK_DEBUG false [get_nets {din_1[25]}]
set_property MARK_DEBUG false [get_nets {din_10[5]}]
set_property MARK_DEBUG false [get_nets {din_10[8]}]
set_property MARK_DEBUG false [get_nets {din_10[13]}]
set_property MARK_DEBUG false [get_nets {din_1[21]}]
set_property MARK_DEBUG false [get_nets {din_7[1]}]
set_property MARK_DEBUG false [get_nets {din_7[3]}]
set_property MARK_DEBUG false [get_nets {din_7[5]}]
set_property MARK_DEBUG false [get_nets {din_7[12]}]
set_property MARK_DEBUG false [get_nets {din_7[14]}]
set_property MARK_DEBUG false [get_nets {din_50[1]}]
set_property MARK_DEBUG false [get_nets {din_6[20]}]
set_property MARK_DEBUG false [get_nets {din_6[7]}]
set_property MARK_DEBUG false [get_nets {din_6[12]}]
set_property MARK_DEBUG false [get_nets {din_6[16]}]
set_property MARK_DEBUG false [get_nets {din_6[24]}]
set_property MARK_DEBUG false [get_nets {din_8[26]}]
set_property MARK_DEBUG false [get_nets {din_60[2]}]
set_property MARK_DEBUG false [get_nets {din_60[6]}]
set_property MARK_DEBUG false [get_nets {din_80[1]}]
set_property MARK_DEBUG false [get_nets {din_80[13]}]
set_property MARK_DEBUG false [get_nets {din_8[2]}]
set_property MARK_DEBUG false [get_nets {din_8[8]}]
set_property MARK_DEBUG false [get_nets {din_8[34]}]
set_property MARK_DEBUG false [get_nets {din_70[11]}]
set_property MARK_DEBUG false [get_nets {din_8[3]}]
set_property MARK_DEBUG false [get_nets {din_8[11]}]
set_property MARK_DEBUG false [get_nets {din_8[18]}]
set_property MARK_DEBUG false [get_nets {din_8[23]}]
set_property MARK_DEBUG false [get_nets {din_70[7]}]
set_property MARK_DEBUG false [get_nets {din_70[8]}]
set_property MARK_DEBUG false [get_nets {din_80[9]}]
set_property MARK_DEBUG false [get_nets {din_5[11]}]
set_property MARK_DEBUG false [get_nets {din_7[21]}]
set_property MARK_DEBUG false [get_nets {din_7[25]}]
set_property MARK_DEBUG false [get_nets {din_20[9]}]
set_property MARK_DEBUG false [get_nets {din_60[12]}]
set_property MARK_DEBUG false [get_nets {din_5[17]}]
set_property MARK_DEBUG false [get_nets {din_5[34]}]
set_property MARK_DEBUG false [get_nets {din_50[9]}]
set_property MARK_DEBUG false [get_nets {din_50[12]}]
set_property MARK_DEBUG false [get_nets {din_60[9]}]
set_property MARK_DEBUG false [get_nets {din_4[5]}]
set_property MARK_DEBUG false [get_nets {din_1[15]}]
set_property MARK_DEBUG false [get_nets {din_1[2]}]
set_property MARK_DEBUG false [get_nets {din_4[1]}]
set_property MARK_DEBUG false [get_nets {din_30[6]}]
set_property MARK_DEBUG false [get_nets {din_4[8]}]
set_property MARK_DEBUG false [get_nets {din_6[2]}]
set_property MARK_DEBUG false [get_nets {din_3[14]}]
set_property MARK_DEBUG false [get_nets {din_10[1]}]
set_property MARK_DEBUG false [get_nets {din_80[11]}]
set_property MARK_DEBUG false [get_nets {din_20[3]}]
set_property MARK_DEBUG false [get_nets {din_3[21]}]
set_property MARK_DEBUG false [get_nets {din_70[1]}]
set_property MARK_DEBUG false [get_nets {din_1[16]}]
set_property MARK_DEBUG false [get_nets {din_5[1]}]
set_property MARK_DEBUG false [get_nets {din_20[6]}]
set_property MARK_DEBUG false [get_nets {din_30[1]}]
set_property MARK_DEBUG false [get_nets {din_30[9]}]
set_property MARK_DEBUG false [get_nets {din_40[8]}]
set_property MARK_DEBUG false [get_nets {din_40[13]}]
set_property MARK_DEBUG false [get_nets {din_70[0]}]
set_property MARK_DEBUG false [get_nets {din_2[6]}]
set_property MARK_DEBUG false [get_nets {din_5[7]}]
set_property MARK_DEBUG false [get_nets {din_30[8]}]
set_property MARK_DEBUG false [get_nets {din_2[24]}]
set_property MARK_DEBUG false [get_nets {din_2[4]}]
set_property MARK_DEBUG false [get_nets {din_2[0]}]
set_property MARK_DEBUG false [get_nets {din_10[12]}]
set_property MARK_DEBUG false [get_nets {din_1[10]}]
set_property MARK_DEBUG false [get_nets {din_1[6]}]
set_property MARK_DEBUG false [get_nets {din_1[24]}]
set_property MARK_DEBUG false [get_nets {din_10[7]}]
set_property MARK_DEBUG false [get_nets {din_2[11]}]
set_property MARK_DEBUG false [get_nets {din_2[15]}]
set_property MARK_DEBUG false [get_nets {din_2[20]}]
set_property MARK_DEBUG false [get_nets {din_3[2]}]
set_property MARK_DEBUG false [get_nets {din_20[2]}]
set_property MARK_DEBUG false [get_nets {din_20[14]}]
set_property MARK_DEBUG false [get_nets {din_3[6]}]
set_property MARK_DEBUG false [get_nets {din_3[10]}]
set_property MARK_DEBUG false [get_nets {din_3[33]}]
set_property MARK_DEBUG false [get_nets {din_4[14]}]
set_property MARK_DEBUG false [get_nets {din_30[0]}]
set_property MARK_DEBUG false [get_nets {din_4[18]}]
set_property MARK_DEBUG false [get_nets {din_4[22]}]
set_property MARK_DEBUG false [get_nets {din_4[26]}]
set_property MARK_DEBUG false [get_nets {din_5[20]}]
set_property MARK_DEBUG false [get_nets {din_40[1]}]
set_property MARK_DEBUG false [get_nets {din_40[5]}]
set_property MARK_DEBUG false [get_nets {din_5[24]}]
set_property MARK_DEBUG false [get_nets {din_50[8]}]
set_property MARK_DEBUG false [get_nets {din_6[9]}]
set_property MARK_DEBUG false [get_nets {din_7[0]}]
set_property MARK_DEBUG false [get_nets {din_7[7]}]
set_property MARK_DEBUG false [get_nets {din_7[13]}]
set_property MARK_DEBUG false [get_nets {din_50[3]}]
set_property MARK_DEBUG false [get_nets {din_60[14]}]
set_property MARK_DEBUG false [get_nets {din_6[19]}]
set_property MARK_DEBUG false [get_nets {din_5[10]}]
set_property MARK_DEBUG false [get_nets {din_6[11]}]
set_property MARK_DEBUG false [get_nets {din_6[15]}]
set_property MARK_DEBUG false [get_nets {din_6[23]}]
set_property MARK_DEBUG false [get_nets {din_6[33]}]
set_property MARK_DEBUG false [get_nets {din_8[19]}]
set_property MARK_DEBUG false [get_nets {din_80[0]}]
set_property MARK_DEBUG false [get_nets {din_80[5]}]
set_property MARK_DEBUG false [get_nets {din_60[1]}]
set_property MARK_DEBUG false [get_nets {din_60[5]}]
set_property MARK_DEBUG false [get_nets {din_8[0]}]
set_property MARK_DEBUG false [get_nets {din_8[7]}]
set_property MARK_DEBUG false [get_nets {din_8[17]}]
set_property MARK_DEBUG false [get_nets {din_70[10]}]
set_property MARK_DEBUG false [get_nets {din_8[1]}]
set_property MARK_DEBUG false [get_nets {din_8[10]}]
set_property MARK_DEBUG false [get_nets {din_8[14]}]
set_property MARK_DEBUG false [get_nets {din_8[22]}]
set_property MARK_DEBUG false [get_nets {din_50[11]}]
set_property MARK_DEBUG false [get_nets {din_70[9]}]
set_property MARK_DEBUG false [get_nets {din_80[6]}]
set_property MARK_DEBUG false [get_nets {din_80[10]}]
set_property MARK_DEBUG false [get_nets {din_5[15]}]
set_property MARK_DEBUG false [get_nets {din_7[17]}]
set_property MARK_DEBUG false [get_nets {din_7[20]}]
set_property MARK_DEBUG false [get_nets {din_7[24]}]
set_property MARK_DEBUG false [get_nets {din_50[4]}]
set_property MARK_DEBUG false [get_nets {din_5[13]}]
set_property MARK_DEBUG false [get_nets {din_5[19]}]
set_property MARK_DEBUG false [get_nets {din_6[5]}]
set_property MARK_DEBUG false [get_nets {din_7[11]}]
set_property MARK_DEBUG false [get_nets {din_50[10]}]
set_property MARK_DEBUG false [get_nets {din_70[5]}]
set_property MARK_DEBUG false [get_nets {din_4[7]}]
set_property MARK_DEBUG false [get_nets {din_4[0]}]
set_property MARK_DEBUG false [get_nets {din_1[1]}]
set_property MARK_DEBUG false [get_nets {din_1[13]}]
set_property MARK_DEBUG false [get_nets {din_6[0]}]
set_property MARK_DEBUG false [get_nets {din_6[1]}]
set_property MARK_DEBUG false [get_nets {din_70[3]}]
set_property MARK_DEBUG false [get_nets {din_4[4]}]
set_property MARK_DEBUG false [get_nets {din_3[11]}]
set_property MARK_DEBUG false [get_nets {din_3[13]}]
set_property MARK_DEBUG false [get_nets {din_10[0]}]
set_property MARK_DEBUG false [get_nets {din_10[4]}]
set_property MARK_DEBUG false [get_nets {din_3[20]}]
set_property MARK_DEBUG false [get_nets {din_7[26]}]
set_property MARK_DEBUG false [get_nets {din_5[4]}]
set_property MARK_DEBUG false [get_nets {din_3[16]}]
set_property MARK_DEBUG false [get_nets {din_5[0]}]
set_property MARK_DEBUG false [get_nets {din_20[4]}]
set_property MARK_DEBUG false [get_nets {din_30[5]}]
set_property MARK_DEBUG false [get_nets {din_30[11]}]
set_property MARK_DEBUG false [get_nets {din_30[12]}]
set_property MARK_DEBUG false [get_nets {din_40[12]}]
set_property MARK_DEBUG false [get_nets {din_60[8]}]
set_property MARK_DEBUG false [get_nets {din_1[20]}]
set_property MARK_DEBUG false [get_nets {din_3[19]}]
set_property MARK_DEBUG false [get_nets {din_5[9]}]
set_property MARK_DEBUG false [get_nets {din_50[15]}]
set_property MARK_DEBUG false [get_nets {din_3[1]}]
set_property MARK_DEBUG false [get_nets {din_1[5]}]
set_property MARK_DEBUG false [get_nets {din_1[8]}]
set_property MARK_DEBUG false [get_nets {din_3[26]}]
set_property MARK_DEBUG false [get_nets {din_40[0]}]
set_property MARK_DEBUG false [get_nets {din_4[13]}]
set_property MARK_DEBUG false [get_nets {din_4[17]}]
set_property MARK_DEBUG false [get_nets {din_4[21]}]
set_property MARK_DEBUG false [get_nets {din_4[25]}]
set_property MARK_DEBUG false [get_nets {din_4[34]}]
set_property MARK_DEBUG false [get_nets {din_5[23]}]
set_property MARK_DEBUG false [get_nets {din_40[4]}]
set_property MARK_DEBUG false [get_nets {din_40[7]}]
set_property MARK_DEBUG false [get_nets {din_5[33]}]
set_property MARK_DEBUG false [get_nets {din_3[8]}]
set_property MARK_DEBUG false [get_nets {din_3[5]}]
set_property MARK_DEBUG false [get_nets {din_2[33]}]
set_property MARK_DEBUG false [get_nets {din_20[1]}]
set_property MARK_DEBUG false [get_nets {din_20[13]}]
set_property MARK_DEBUG false [get_nets {din_2[23]}]
set_property MARK_DEBUG false [get_nets {din_2[19]}]
set_property MARK_DEBUG false [get_nets {din_2[14]}]
set_property MARK_DEBUG false [get_nets {din_2[10]}]
set_property MARK_DEBUG false [get_nets {din_2[3]}]
set_property MARK_DEBUG false [get_nets {din_1[33]}]
set_property MARK_DEBUG false [get_nets {din_10[9]}]
set_property MARK_DEBUG false [get_nets {din_10[11]}]
set_property MARK_DEBUG false [get_nets {din_10[15]}]
set_property MARK_DEBUG false [get_nets {din_1[23]}]
set_property MARK_DEBUG false [get_nets {din_7[9]}]
set_property MARK_DEBUG false [get_nets {din_7[33]}]
set_property MARK_DEBUG false [get_nets {din_60[15]}]
set_property MARK_DEBUG false [get_nets {din_6[22]}]
set_property MARK_DEBUG false [get_nets {din_6[14]}]
set_property MARK_DEBUG false [get_nets {din_6[10]}]
set_property MARK_DEBUG false [get_nets {din_6[18]}]
set_property MARK_DEBUG false [get_nets {din_6[26]}]
set_property MARK_DEBUG false [get_nets {din_7[34]}]
set_property MARK_DEBUG false [get_nets {din_60[0]}]
set_property MARK_DEBUG false [get_nets {din_60[4]}]
set_property MARK_DEBUG false [get_nets {din_80[4]}]
set_property MARK_DEBUG false [get_nets {din_8[6]}]
set_property MARK_DEBUG false [get_nets {din_8[16]}]
set_property MARK_DEBUG false [get_nets {din_60[7]}]
set_property MARK_DEBUG false [get_nets {din_70[14]}]
set_property MARK_DEBUG false [get_nets {din_7[16]}]
set_property MARK_DEBUG false [get_nets {din_8[9]}]
set_property MARK_DEBUG false [get_nets {din_8[13]}]
set_property MARK_DEBUG false [get_nets {din_8[21]}]
set_property MARK_DEBUG false [get_nets {din_8[25]}]
set_property MARK_DEBUG false [get_nets {din_70[6]}]
set_property MARK_DEBUG false [get_nets {din_70[15]}]
set_property MARK_DEBUG false [get_nets {din_80[8]}]
set_property MARK_DEBUG false [get_nets {din_5[14]}]
set_property MARK_DEBUG false [get_nets {din_7[19]}]
set_property MARK_DEBUG false [get_nets {din_7[23]}]
set_property MARK_DEBUG false [get_nets {din_50[13]}]
set_property MARK_DEBUG false [get_nets {din_2[5]}]
set_property MARK_DEBUG false [get_nets {din_6[3]}]
set_property MARK_DEBUG false [get_nets {din_6[6]}]
set_property MARK_DEBUG false [get_nets {din_7[8]}]
set_property MARK_DEBUG false [get_nets {din_7[10]}]
set_property MARK_DEBUG false [get_nets {din_50[7]}]
set_property MARK_DEBUG false [get_nets {din_4[3]}]
set_property MARK_DEBUG false [get_nets {din_1[12]}]
set_property MARK_DEBUG false [get_nets {din_1[0]}]
set_property MARK_DEBUG false [get_nets {din_2[16]}]
set_property MARK_DEBUG false [get_nets {din_30[15]}]
set_property MARK_DEBUG false [get_nets {din_4[9]}]
set_property MARK_DEBUG false [get_nets {din_50[5]}]
set_property MARK_DEBUG false [get_nets {din_70[2]}]
set_property MARK_DEBUG false [get_nets {din_1[19]}]
set_property MARK_DEBUG false [get_nets {din_3[18]}]
set_property MARK_DEBUG false [get_nets {din_30[3]}]
set_property MARK_DEBUG false [get_nets {din_10[3]}]
set_property MARK_DEBUG false [get_nets {din_20[10]}]
set_property MARK_DEBUG false [get_nets {din_1[34]}]
set_property MARK_DEBUG false [get_nets {din_5[3]}]
set_property MARK_DEBUG false [get_nets {din_20[8]}]
set_property MARK_DEBUG false [get_nets {din_30[4]}]
set_property MARK_DEBUG false [get_nets {din_30[10]}]
set_property MARK_DEBUG false [get_nets {din_30[13]}]
set_property MARK_DEBUG false [get_nets {din_40[11]}]
set_property MARK_DEBUG false [get_nets {din_40[15]}]
set_property MARK_DEBUG false [get_nets {din_3[15]}]
set_property MARK_DEBUG false [get_nets {din_5[6]}]
set_property MARK_DEBUG false [get_nets {din_50[14]}]
set_property MARK_DEBUG false [get_nets {din_2[18]}]
set_property MARK_DEBUG false [get_nets {din_1[4]}]
set_property MARK_DEBUG false [get_nets {din_1[7]}]
set_property MARK_DEBUG false [get_nets {din_1[22]}]
set_property MARK_DEBUG false [get_nets {din_1[26]}]
set_property MARK_DEBUG false [get_nets {din_2[2]}]
set_property MARK_DEBUG false [get_nets {din_10[14]}]
set_property MARK_DEBUG false [get_nets {din_10[6]}]
set_property MARK_DEBUG false [get_nets {din_10[10]}]
set_property MARK_DEBUG false [get_nets {din_2[8]}]
set_property MARK_DEBUG false [get_nets {din_2[13]}]
set_property MARK_DEBUG false [get_nets {din_2[22]}]
set_property MARK_DEBUG false [get_nets {din_2[26]}]
set_property MARK_DEBUG false [get_nets {din_3[0]}]
set_property MARK_DEBUG false [get_nets {din_20[0]}]
set_property MARK_DEBUG false [get_nets {din_20[12]}]
set_property MARK_DEBUG false [get_nets {din_3[4]}]
set_property MARK_DEBUG false [get_nets {din_3[7]}]
set_property MARK_DEBUG false [get_nets {din_3[25]}]
set_property MARK_DEBUG false [get_nets {din_3[34]}]
set_property MARK_DEBUG false [get_nets {din_4[12]}]
set_property MARK_DEBUG false [get_nets {din_4[16]}]
set_property MARK_DEBUG false [get_nets {din_4[20]}]
set_property MARK_DEBUG false [get_nets {din_4[24]}]
set_property MARK_DEBUG false [get_nets {din_40[3]}]
set_property MARK_DEBUG false [get_nets {din_40[9]}]
set_property MARK_DEBUG false [get_nets {din_5[22]}]
set_property MARK_DEBUG false [get_nets {din_5[26]}]
set_property MARK_DEBUG false [get_nets {din_7[2]}]
set_property MARK_DEBUG false [get_nets {din_7[6]}]
set_property MARK_DEBUG false [get_nets {din_7[15]}]
set_property MARK_DEBUG false [get_nets {din_60[10]}]
set_property MARK_DEBUG false [get_nets {din_80[12]}]
set_property MARK_DEBUG false [get_nets {din_6[21]}]
set_property MARK_DEBUG false [get_nets {din_6[13]}]
set_property MARK_DEBUG false [get_nets {din_6[8]}]
set_property MARK_DEBUG false [get_nets {din_6[17]}]
set_property MARK_DEBUG false [get_nets {din_6[25]}]
set_property MARK_DEBUG false [get_nets {din_6[34]}]
set_property MARK_DEBUG false [get_nets {din_7[4]}]
set_property MARK_DEBUG false [get_nets {din_60[3]}]
set_property MARK_DEBUG false [get_nets {din_8[33]}]
set_property MARK_DEBUG false [get_nets {din_80[3]}]
set_property MARK_DEBUG false [get_nets {din_80[14]}]
set_property MARK_DEBUG false [get_nets {din_8[4]}]
set_property MARK_DEBUG false [get_nets {din_8[15]}]
set_property MARK_DEBUG false [get_nets {din_70[12]}]
set_property MARK_DEBUG false [get_nets {din_5[16]}]
set_property MARK_DEBUG false [get_nets {din_8[5]}]
set_property MARK_DEBUG false [get_nets {din_8[12]}]
set_property MARK_DEBUG false [get_nets {din_8[20]}]
set_property MARK_DEBUG false [get_nets {din_8[24]}]
set_property MARK_DEBUG false [get_nets {din_70[13]}]
set_property MARK_DEBUG false [get_nets {din_80[2]}]
set_property MARK_DEBUG false [get_nets {din_80[7]}]
set_property MARK_DEBUG false [get_nets {din_3[23]}]
set_property MARK_DEBUG false [get_nets {din_5[12]}]
set_property MARK_DEBUG false [get_nets {din_7[18]}]
set_property MARK_DEBUG false [get_nets {din_7[22]}]
set_property MARK_DEBUG false [get_nets {din_50[2]}]
set_property MARK_DEBUG false [get_nets {din_60[13]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_1[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_8[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_7[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[9]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[6]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[4]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_6[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[10]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[7]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[8]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[5]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[3]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_4[1]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_3[11]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[2]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_2[0]}]
set_property MARK_DEBUG false [get_nets {reg_time_gap_5[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_7[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_1[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_8[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_2[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_3[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_4[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_6[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/memout_5[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_end_seq_addr[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[0]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[11]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[9]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[4]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[15]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[5]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[2]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[3]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_4[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_3[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[13]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_2[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[12]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_8[14]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[7]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_1[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[1]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_5[8]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_6[6]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[10]}]
set_property MARK_DEBUG true [get_nets {u_memory_space/reg_time_gap_7[12]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_clk_gen/inst/uart_clkg]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_memory_space/reg_end_seq_addr[0]} {u_memory_space/reg_end_seq_addr[1]} {u_memory_space/reg_end_seq_addr[2]} {u_memory_space/reg_end_seq_addr[3]} {u_memory_space/reg_end_seq_addr[4]} {u_memory_space/reg_end_seq_addr[5]} {u_memory_space/reg_end_seq_addr[6]} {u_memory_space/reg_end_seq_addr[7]} {u_memory_space/reg_end_seq_addr[8]} {u_memory_space/reg_end_seq_addr[9]} {u_memory_space/reg_end_seq_addr[10]} {u_memory_space/reg_end_seq_addr[11]} {u_memory_space/reg_end_seq_addr[12]} {u_memory_space/reg_end_seq_addr[13]} {u_memory_space/reg_end_seq_addr[14]} {u_memory_space/reg_end_seq_addr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_memory_space/reg_time_gap_2[0]} {u_memory_space/reg_time_gap_2[1]} {u_memory_space/reg_time_gap_2[2]} {u_memory_space/reg_time_gap_2[3]} {u_memory_space/reg_time_gap_2[4]} {u_memory_space/reg_time_gap_2[5]} {u_memory_space/reg_time_gap_2[6]} {u_memory_space/reg_time_gap_2[7]} {u_memory_space/reg_time_gap_2[8]} {u_memory_space/reg_time_gap_2[9]} {u_memory_space/reg_time_gap_2[10]} {u_memory_space/reg_time_gap_2[11]} {u_memory_space/reg_time_gap_2[12]} {u_memory_space/reg_time_gap_2[13]} {u_memory_space/reg_time_gap_2[14]} {u_memory_space/reg_time_gap_2[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_memory_space/reg_time_gap_3[0]} {u_memory_space/reg_time_gap_3[1]} {u_memory_space/reg_time_gap_3[2]} {u_memory_space/reg_time_gap_3[3]} {u_memory_space/reg_time_gap_3[4]} {u_memory_space/reg_time_gap_3[5]} {u_memory_space/reg_time_gap_3[6]} {u_memory_space/reg_time_gap_3[7]} {u_memory_space/reg_time_gap_3[8]} {u_memory_space/reg_time_gap_3[9]} {u_memory_space/reg_time_gap_3[10]} {u_memory_space/reg_time_gap_3[11]} {u_memory_space/reg_time_gap_3[12]} {u_memory_space/reg_time_gap_3[13]} {u_memory_space/reg_time_gap_3[14]} {u_memory_space/reg_time_gap_3[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_memory_space/memout_2[0]} {u_memory_space/memout_2[1]} {u_memory_space/memout_2[2]} {u_memory_space/memout_2[3]} {u_memory_space/memout_2[4]} {u_memory_space/memout_2[5]} {u_memory_space/memout_2[6]} {u_memory_space/memout_2[7]} {u_memory_space/memout_2[8]} {u_memory_space/memout_2[9]} {u_memory_space/memout_2[10]} {u_memory_space/memout_2[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 12 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_memory_space/memout_1[0]} {u_memory_space/memout_1[1]} {u_memory_space/memout_1[2]} {u_memory_space/memout_1[3]} {u_memory_space/memout_1[4]} {u_memory_space/memout_1[5]} {u_memory_space/memout_1[6]} {u_memory_space/memout_1[7]} {u_memory_space/memout_1[8]} {u_memory_space/memout_1[9]} {u_memory_space/memout_1[10]} {u_memory_space/memout_1[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {u_memory_space/reg_time_gap_1[0]} {u_memory_space/reg_time_gap_1[1]} {u_memory_space/reg_time_gap_1[2]} {u_memory_space/reg_time_gap_1[3]} {u_memory_space/reg_time_gap_1[4]} {u_memory_space/reg_time_gap_1[5]} {u_memory_space/reg_time_gap_1[6]} {u_memory_space/reg_time_gap_1[7]} {u_memory_space/reg_time_gap_1[8]} {u_memory_space/reg_time_gap_1[9]} {u_memory_space/reg_time_gap_1[10]} {u_memory_space/reg_time_gap_1[11]} {u_memory_space/reg_time_gap_1[12]} {u_memory_space/reg_time_gap_1[13]} {u_memory_space/reg_time_gap_1[14]} {u_memory_space/reg_time_gap_1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {u_memory_space/reg_time_gap_8[0]} {u_memory_space/reg_time_gap_8[1]} {u_memory_space/reg_time_gap_8[2]} {u_memory_space/reg_time_gap_8[3]} {u_memory_space/reg_time_gap_8[4]} {u_memory_space/reg_time_gap_8[5]} {u_memory_space/reg_time_gap_8[6]} {u_memory_space/reg_time_gap_8[7]} {u_memory_space/reg_time_gap_8[8]} {u_memory_space/reg_time_gap_8[9]} {u_memory_space/reg_time_gap_8[10]} {u_memory_space/reg_time_gap_8[11]} {u_memory_space/reg_time_gap_8[12]} {u_memory_space/reg_time_gap_8[13]} {u_memory_space/reg_time_gap_8[14]} {u_memory_space/reg_time_gap_8[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {u_memory_space/reg_time_gap_5[0]} {u_memory_space/reg_time_gap_5[1]} {u_memory_space/reg_time_gap_5[2]} {u_memory_space/reg_time_gap_5[3]} {u_memory_space/reg_time_gap_5[4]} {u_memory_space/reg_time_gap_5[5]} {u_memory_space/reg_time_gap_5[6]} {u_memory_space/reg_time_gap_5[7]} {u_memory_space/reg_time_gap_5[8]} {u_memory_space/reg_time_gap_5[9]} {u_memory_space/reg_time_gap_5[10]} {u_memory_space/reg_time_gap_5[11]} {u_memory_space/reg_time_gap_5[12]} {u_memory_space/reg_time_gap_5[13]} {u_memory_space/reg_time_gap_5[14]} {u_memory_space/reg_time_gap_5[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 12 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {u_memory_space/memout_7[0]} {u_memory_space/memout_7[1]} {u_memory_space/memout_7[2]} {u_memory_space/memout_7[3]} {u_memory_space/memout_7[4]} {u_memory_space/memout_7[5]} {u_memory_space/memout_7[6]} {u_memory_space/memout_7[7]} {u_memory_space/memout_7[8]} {u_memory_space/memout_7[9]} {u_memory_space/memout_7[10]} {u_memory_space/memout_7[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 7 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {seq_addr_8[0]} {seq_addr_8[1]} {seq_addr_8[2]} {seq_addr_8[3]} {seq_addr_8[4]} {seq_addr_8[5]} {seq_addr_8[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe10]
set_property port_width 7 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {seq_addr_2[0]} {seq_addr_2[1]} {seq_addr_2[2]} {seq_addr_2[3]} {seq_addr_2[4]} {seq_addr_2[5]} {seq_addr_2[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 12 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {u_memory_space/memout_8[0]} {u_memory_space/memout_8[1]} {u_memory_space/memout_8[2]} {u_memory_space/memout_8[3]} {u_memory_space/memout_8[4]} {u_memory_space/memout_8[5]} {u_memory_space/memout_8[6]} {u_memory_space/memout_8[7]} {u_memory_space/memout_8[8]} {u_memory_space/memout_8[9]} {u_memory_space/memout_8[10]} {u_memory_space/memout_8[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe12]
set_property port_width 7 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {seq_addr_1[0]} {seq_addr_1[1]} {seq_addr_1[2]} {seq_addr_1[3]} {seq_addr_1[4]} {seq_addr_1[5]} {seq_addr_1[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list btn0_int]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list debounce_switch_inst_n_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list u_seq_ctr_1/manchester_wren10_out]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list trig_1]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets uart_clkg]
